#
# User Interface commands
#

UIOBJS  = ui_command.o ui_cmddisp.o ui_envcmds.o ui_devcmds.o \
	  ui_netcmds.o ui_tcpcmds.o ui_memcmds.o ui_loadcmds.o ui_pcicmds.o \
	  ui_examcmds.o ui_flash.o ui_misccmds.o ui_toyclock.o \
          ui_test_disk.o ui_test_ether.o ui_test_flash.o ui_test_uart.o \
          ui_vxboot.o ui_miiphycmds.o ui_ptable.o

