
#
# Makefile for USB stuff
#

ALLOBJS += usbmain.o ohci.o usbd.o usbdevs.o usbhub.o usbdebug.o usbhid.o \
           usbmass.o usbserial.o usbeth.o
ALLOBJS += dev_usb_klsi.o dev_usb_rtek.o dev_usb_catc.o dev_usb_pegasus.o \
	   dev_usb_asix.o
CFLAGS += -DCFG_USB=1
