
#
# This is just a Makefile fragment -- it is included by the master
# makefile, cfe.mk
#
# This file should just append object file names to "ALLOBJS"
#

BSPOBJS +=  bcm91125pcix_init.o bcm91125pcix_devs.o
ALLOBJS +=  ui_bcm91125pcix.o 

SMBDEVS = 24lc128 m41t81clock

ALLOBJS +=  ui_clkgen.o
